### PR TITLE
Use src folder for page directory.

### PR DESCRIPTION
**Pull request by johnforte**
@jescalan I built off your branch a bit, but I feel that storing the page dir as with the plugins options just felt a bit cleaner. I also used your test, which had a bug in it. The layout pointed to the pages folder not the src/pages folder so I corrected that.

#51

### CODE REVIEW

**Comment by jescalan** [comment]
Beautiful, thank you so much @johnforte! Was getting a little burned out on this one haha, so appreciate the push across the line. I think the only thing left here would be documenting the `usesSrc` option in the readme, unless you also had other things you wanted to add?

**Comment by johnforte** [comment]
@jescalan I added the docs, but can you also kick off the CI process before merging.

**Comment by jescalan** [comment]
Yeah for sure - I think it needs to be a branch off my repo rather than a fork for the CI to run - I can add you as a contributor so you can make a branch, or I can copy the commits into a branch and open another PR - any preference?

**Comment by johnforte** [comment]
You can copy it.

I believe all you need is to pull the patch file like so https://patch-diff.githubusercontent.com/raw/hashicorp/next-mdx-enhanced/pull/73.patch then you can do git apply to a new branch. That should preserve the history correctly.

**Comment by benedfit** [comment]
Looking forward to this landing

**Comment by jescalan** [comment]
This will land this week

**Comment by jescalan** [comment]
CI passing here: https://github.com/hashicorp/next-mdx-enhanced/pull/79

**Pull request merged**
