### PR TITLE
Use Dockerhub Mirror

### PR DESCRIPTION
**Pull request by RussellRollins**
Dockerhub is going to rate limit unauthenticated pulls.

### CODE REVIEW

**Comment by jescalan** [comment]
I don't think this is necessary for this repo, since it uses a circleci-native image. Am I mistaken here?

**Comment by RussellRollins** [comment]
@jescalan from the [CircleCI FAQ](https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ):

> I use CircleCI convenience images, does this affect me?
> 
> No, as mentioned previously CircleCI has partnered with Docker to ensure that our users can continue to access Docker Hub without rate limits.
>
> However, these rate limits may go into effect for CircleCI users in the future. That’s why we’re encouraging you and your team to add Docker Hub authentication to your CircleCI configuration and consider upgrading your Docker Hub plan, as appropriate, to prevent any impact from rate limits in the future.

While you will likely be fine in the short term, Circle is non-committal about how long you'll be able to pull images, including their own, without authentication.

**Comment by jescalan** [comment]
That's fair, I feel like they will likely give another warning if that is going to happen though, right?

**Comment by RussellRollins** [comment]
@jescalan at this point in the process, Circle has changed their story on short notice a few times. Perhaps I am just a bit disenchanted with them.

You're welcome to take or leave this PR, just wanted to make sure we had options for mitigations in place.

**Pull request closed without merging**
