### PR TITLE
`src` folder support

### PR DESCRIPTION
**Pull request by jescalan**
Branching off the existing PR #52 to take this one across the finish line!

### CODE REVIEW

**Comment by jescalan** [comment]
@jensmeindertsma @odensc Just want to get your eyes on this. I was slightly concerned that #52 was totally broken despite your reports of it working fine - a function was used that was not imported in `index.js`.

I also made a few ergonomic code changes to make things hopefully a little more clear. Tests are now passing but I think I'd like to also run a few extra real-life integrations here to make extra sure that we're clear before shipping given the recent instability.

**Comment by jensmeindertsma** [comment]
Cool!

**Comment by odensc** [comment]
@jescalan I just dropped this into my existing project and I'm having one issue. It works fine with `import`, but in my Layout component's frontmatter, I'm getting a path like `home/oden/Dev/odensc.com/src/pages/2019/05/01/...` (as opposed to `pages/2019/05/01/...`).

I tracked it down to [this line](https://github.com/hashicorp/next-mdx-enhanced/blob/c45c39178aa22818e69bcef8ffb09dbea02a23b8/loader.js#L31) being incorrect. It should read `options.mdxEnhancedPluginOptions.usesSrc`.

**Comment by jescalan** [comment]
@odensc thank you, excellent feedback and review. I will patch that up now. Really grateful for your time testing this with windows on a real-world project, it makes a huge difference to have this extra peace of mind that things are working!

**Comment by johnforte** [comment]
I am seeing an issue on the first run, it looks to be a timing issue. Cause the JSON file below is there, but on the first run, it says it can't find it. After that, I get no more issues.

I am using external .babelrc

.babelrc file
```
{
  "presets": ["next/babel"],
  "plugins": ["import-glob-array"]
}
```

error
```
./src/pages/articles.tsx
Module not found: Can't resolve '/Users/johnforte/Programs/site/.mdx-data/4b3e1a101fe131fe89291c14cb98fbf5.json' in '/Users/johnforte/Programs/site/src/pages'


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/johnforte/Programs/site/node_modules/next/dist/build/index.js:13:917)

```

**Comment by jescalan** [comment]
@johnforte - is that only when using the version on this branch, or is this an issue for you in general?

**Comment by johnforte** [comment]
> @johnforte - ~is that only when using the version on this branch, or is this an issue for you in general?~
> 
> Is there any way you could post a minimal reproduction for this? it would be super helpful!

Basically I tracked it down to a sort method I use on a property of the frontMatter, that is causing the issue. Once removed then everything is happy again. Still digging deeper into why. But for now, I feel like it shouldn't be a show stopper.

**Comment by jescalan** [comment]
Ah ok, thank you! I will get this merged and shipped out then. Thanks again for taking the time to review and evaluate 🙏🏼

**Comment by jescalan** [comment]
aaand never mind tests failing, back to the drawing board

**Comment by jescalan** [comment]
Closing in favor of #73

**Pull request closed without merging**
