### PR TITLE
Export all named exports from layout

### PR DESCRIPTION
**Pull request by zephraph**
There's an [RFC](https://github.com/zeit/next.js/issues/9524) in next (that's released in 9.X as unstable) that improves static generation. The api for this is exposed by having a top level export on the nextjs page

```javascript
// pages/index.js

// getStaticProps is only called server-side
export async function getStaticProps(context) {
  return {
    // Unlike `getInitialProps` the props are returned under a props key
    // The reasoning behind this is that there's potentially more options
    // that will be introduced in the future.
    // For example to allow you to further control behavior per-page.
    props: {}
  };
}
```

This is unliked the previous API which was attached to the default export. In order to take advantage of this API with layouts, we need to forward all named exports from the layout. This will allow a layout file to provide `getStaticProps`, `getStaticPaths`, and `getServerProps` to hook into the corresponding optimizations.

### CODE REVIEW

**Comment by zephraph** [comment]
Hey @jescalan, totally my bad here but it looks like this isn't possible until https://github.com/mdx-js/mdx/pull/911. 

911 indeed.

`remark-mdx` doesn't yet support the `export * from 'blah'` syntax. I'm not sure what happened because I _know_ I was using this last night. If you could revert this for now I'll open up another PR (with tests!) when the upstream fix is merged and released. 

Thanks (and sorry again!)

**Comment by jescalan** [comment]
Ok what's the status here? Do i need to revert these changes? It seemed like a small innocent addition but if this is breaking the latest publish I need to roll it back.

**Comment by jescalan** [comment]
Never mind we're clear I didn't push a new version with only this change

**Comment by zephraph** [comment]
@jescalan the change was reverted in #39. That said, my fix got merged upstream in [mdx v1.5.4](https://github.com/mdx-js/mdx/releases/tag/v1.5.4). I'll do a new PR with a dependency bump, the change re-added, and a test. 

It's all coming together. Very exciting.

**Pull request merged**
